version: "3.8"
services:
  postgres-db:
    container_name: lof_dev
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lof_dev
    ports:
      - 5432:5432
