name: Deploy to GitHub Pages

on:
  push:
    branches: [main]  # Triggers on push to main 
  workflow_dispatch:  

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build
        env:
          VITE_APPWRITE_PROJECT_ID: ${{ secrets.APPWRITE_LOF_PROJECT_ID }}
          VITE_APPWRITE_DATABASE_ID: ${{ secrets.APPWRITE_LOF_DB_ID }}
          VITE_APPWRITE_COLLECTION_ID: ${{ secrets.APPWRITE_TEAM_COLLECTION_ID }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist  # built files
          branch: gh-pages  # branch to deploy to
          clean: true  # only built code